// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707032620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Cow", b =>
                {
                    b.Property<int>("CowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "cowId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CowId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "birthDate");

                    b.Property<int>("BreedId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "breedId");

                    b.Property<DateTime>("DeathDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "deathDate");

                    b.Property<int>("Eartag")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "eartag");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isFemale");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isPregnant");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Rfid")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rfid");

                    b.HasKey("CowId");

                    b.ToTable("Cattle");
                });
#pragma warning restore 612, 618
        }
    }
}
